---
name: WaterGuru API
version: 0.0.1
slug: waterguru-api
description: API Bridge to WaterGuru SENSE cloud services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: https://github.com/johnpdowling/hassio-addons/tree/master/waterguru-api
startup: application
boot: auto
init: false
ports:
  53255/tcp: 53255
ports_description:
  53255/tcp: API access port
options: 
  email: "user@example.com"
  password: "P@$$w0rd"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  email: str
  password: str
